### ISSUE TITLE
Error: Invalid GUILayout state in MultiPlayEditor view

### ISSUE THREAD

**Issue by Radivarig** [muammar-yacoob/MultiPlay#1]
```
GUI Error: Invalid GUILayout state in MultiPlayEditor view. Verify that all layout Begin/End calls match
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```
Found some discussion on this error here:
https://forum.unity.com/threads/avoiding-you-getting-insane-because-of-invalid-guilayout-state-errors.1429669/

**Comment by Radivarig** [comment]
This is only happening when there's a scrollbar

**Comment by Radivarig** [comment]
This happens consistently when the Settings section is collapsed, uncollapsing it stops the error.

**Comment by muammar-yacoob** [comment]
Fixed. Thank you for your feedback ❤️
