### ISSUE TITLE
IOException: Sharing violation for Library\Search\transactions.db

### ISSUE THREAD

**Issue by Radivarig** [muammar-yacoob/MultiPlay#2]
```
IOException: Sharing violation on path <PROJECT_PATH>\Library\Search\transactions.db
```

Maybe this could be solved by adding a list of file names to be duplicated instead of linked?

**Comment by muammar-yacoob** [comment]
Good observation, this is a new issue that only applies to newer versions of Unity.
I'm afraid it's something the application will have to live with for now for simplicity instead of checking every subfile especially when the editor files keep changing a lot in later versions.
