### ISSUE TITLE
[Request] Settings improvements

### ISSUE THREAD

**Issue by Radivarig** [muammar-yacoob/MultiPlay#3]
1. When installed under Packages, changes to the read-only MultiPlaySettings.asset are not serialized
2. Better default name for the `ClonesPath` ~~is `./MultiPlay`, so that it is relative to the project~~
3. Field `maxNumberOfClones` can be replaced by a + button at the end of list of clones

**Comment by Radivarig** [comment]
2. actually relative to project makes the IDEs show all the files from clones folder, so needs a better solution.
Maybe some combination of `%AppData%` and project Folder name

**Comment by Radivarig** [comment]
I am blind, I haven't noticed the Browse button... I think that's sufficient for 2.

**Comment by muammar-yacoob** [comment]
Not sure I understand the problem but I'm closing the issue based on my understanding that the browse button does it for now. Please feel free to re-open a new issue if need be.
